name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    # nothing here

env:
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build-msvc:
    strategy:
      matrix:
        build_type: [Release]
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          spectre: true


      - name: Configure CMake
        run: cmake -G "Ninja" -B "${{env.BUILD_DIR}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON

      - name: Build
        working-directory: ${{env.BUILD_DIR}}
        run: cmake --build . --config ${{matrix.build_type}} -t LuxMipmapProcessor -- -j%NUMBER_OF_PROCESSORS%

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LuxMipmapProcessor-Windows-msvc-${{matrix.build_type}}
          path: |
            ${{env.BUILD_DIR}}/*.exe
            ${{env.BUILD_DIR}}/*.dll
          retention-days: 7

  build-linux:
    strategy:
      matrix:
        build_type: [Release]
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Necessary Packages
        run: sudo apt update && sudo apt install -y cmake build-essential ninja-build

      - name: Install GCC
        if: ${{ matrix.compiler == 'gcc' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 12
          platform: x64

      - name: Install Clang
        if: ${{ matrix.compiler == 'clang' }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64

      - name: Configure CMake
        run: cmake -G "Ninja" -B "${{env.BUILD_DIR}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        working-directory: ${{env.BUILD_DIR}}
        run: cmake --build . --config ${{matrix.build_type}} -t LuxMipmapProcessor -- -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LuxMipmapProcessor-Linux-${{matrix.compiler}}-${{matrix.build_type}}
          path: |
            ${{env.BUILD_DIR}}/LuxMipmapProcessor
            ${{env.BUILD_DIR}}/*.so*
          retention-days: 7
